#! /bin/bash

# if [[ -f $0 ]]; then
#   echo "file exists ..."
# else
#   echo "nothing"
# fi
# if [[ -d $0 ]]; then
#   echo "file exists ..."
# else
#   echo "nothing"
# fi

read -p "Number? " n
if (( n > 10 )); then
  echo "bigger than 10"
else
  echo "less less"
fi