#!/bin/bash

read -p "Signal color? " color
case "$color" in
  red)
    echo "stop"
    ;;
  # blue)
  blue|green)
    echo "go"
    ;;
  yellow)
    echo "caution"
    ;;
  *)
    echo "wrong signal"
esac