#! /bin/bash

# read -p "Name? " name
# if [ "$name" = "isaac" ]; then
#   echo "welcome"
# elif [ "$name" = "test" ]; then
#   echo "welcome, too"
# else
#   echo "you are not allowed"
# fi

read -p "Name? " name
# if [[ $name = "isaac" ]]; then
#   echo "welcome"
# fi
# if [[ -z $name ]]; then
#   echo "empty ...."
# fi
if [[ $name =~ ^t ]]; then
  echo "starts with t...."
fi